name: dynamic_button
description: A customizable Flutter UI library for dynamic buttons, chips, segmented controls, and interactive selection components.
version: 1.0.1

homepage: https://github.com/mowlashuvo/dynamic_button
repository: https://github.com/mowlashuvo/dynamic_button
issue_tracker: https://github.com/mowlashuvo/dynamic_button/issues

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

topics:
  - flutter
  - button
  - chips
  - segmented-control
  - ui

flutter: