name: dynamic_button
description: A production-ready Flutter UI library for building customizable buttons, chips, segmented controls, filter buttons, and selectable components with animations, themes, and generic item support.
version: 0.1.0

homepage: https://github.com/mowlashuvo/dynamic_button
repository: https://github.com/mowlashuvo/dynamic_button
issue_tracker: https://github.com/mowlashuvo/dynamic_button/issues

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

topics:
  - flutter
  - button
  - chips
  - segmented-control
  - ui

flutter: